blank_issues_enabled: false
contact_links:
  - name: Frage / Diskussion
    url: https://github.com/amgiparker/open-jf-coach/discussions
    about: Für allgemeine Fragen bitte die Discussions nutzen.
